name: Unit test

on: [push]

env:
  QIWIS_VERSION: v3.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install coverage
    - name: Add dependencies about external libraries
      run: |
        pip install h5py
        pip install pyqt5
        pip install requests
        pip install websockets
        pip install numpy
        pip install pyqtgraph
        sudo apt-get install python3-pyqt5
        pip install git+https://github.com/m-labs/sipyco.git
        pip install git+https://github.com/snu-quiqcl/qiwis.git@${{ env.QIWIS_VERSION }}
    - name: Run the unit tests and check coverage
      run: |
        xvfb-run `which coverage` run --source=iquip/ -m unittest discover -b
        xvfb-run `which coverage` report
